include:
  - local: "/includes/java-mvn.yml"
  - local: "/includes/docker.yml"
  - local: "/includes/vault.yml"
  - local: "/includes/rules.yml"

default:
  image: alpine:latest
#  tags:
#    - ADD_CUSTOM_TAG_HERE

cache:
  paths:
    - .m2/repository/
    - node_modules

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${QUAY_ROOT_URL}/${PROJECT_PATH}"


stages:
  - read-secret
  - quality-app
  - build-app
  - docker-test
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

quality_app:
  variables:
    BUILD_IMAGE_NAME: maven:3.8-openjdk-17
    WORKING_DIR: .
  stage: quality-app
  extends:
    - .java:sonar

package-app:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    MAVEN_CLI_OPTS: ""
    MVN_CONFIG_FILE: $MVN_CONFIG
    BUILD_IMAGE_NAME: maven:3.8-openjdk-17
    WORKING_DIR: .
    ARTEFACT_DIR: ./target/*.jar

  stage: build-app
  extends:
    - .java:build



docker-test:
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: app-java-forge-dso-demo
  stage: docker-test
  extends:
    - .buildah:test

docker-build:
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: app-java-forge-dso-demo
  stage: docker-build
  extends:
    - .kaniko:build
