spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_dso
    username: demo_dso
    password: demo_dso
  liquibase:
    change-log: classpath:db/changelog/0000-initial_schema.xml

server:
  port: 9090